import { AxiosResponse } from "axios";
import { api } from "../api";

// Generated by https://quicktype.io

export interface ResponseListaUsuarios {
  ok: boolean;
  message: string;
  data: DatumListaUsuarios[];
}

export interface DatumListaUsuarios {
  id: string;
  nombre: string;
  correoElectronico: string;
  contrasena: string;
  ultimaConexion: string;
  imagenPerfil: null | string;
  estado: string;
  id_role: null | string;
  createdAt: string;
  updatedAt: string;
  roles: Roles | null;
}

export interface Roles {
  id: string;
  nombre: string;
  descripcion: string;
}

export const listaUsuarios = async (): Promise<
  DatumListaUsuarios[] | undefined
> => {
  try {
    const { data }: AxiosResponse = await api.get(
      "/control-usuarios/users/show-all"
    );

    if (!data) throw new Error("Error");
    return data.data;
  } catch (error) {
    console.log(error);
  }
};

interface RequestActivate {
  id: string;
}
export const activarODesactivarUser = async (dataBody: RequestActivate) => {
  try {
    const { data }: AxiosResponse = await api.post(
      "/control-usuarios/users/active-inactive",
      {
        id: dataBody.id,
      }
    );

    if (!data) throw new Error("Error");
    if (!data.ok) throw new Error(data.message);

    return data;
  } catch (error) {
    console.log(error);
  }
};
